global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'monitoring'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.199.72:8080']